### ISSUE TITLE
Does this model continue to improve in large scale regime?

### ISSUE THREAD

**Issue by DaehanKim** [Guitaricet/peft_pretraining#1]
hi! Thank you for this insightful work.
I wonder how your research on large language models is going on.
Is your 350M run finished? 
also I'm curious about how good billion scale models can be.
Do you have any plans to scale up your experiments?

**Comment by Guitaricet** [comment]
Hi! Thanks for the interest!
Our latest results show that when applied to 350M model, ReLoRA can perform just as well as regular training.
We are currently scaling up ReLoRA to test it on Pythia-1B with Eleuther.Ai. You can see the 1B code in dev branch.

![W B Chart 7_19_2023, 11_00_07 AM](https://github.com/Guitaricet/peft_pretraining/assets/2821124/2600c0e2-ee81-4ead-b341-f2e7ab6a600b)

**Comment by DumoeDss** [comment]
> Hi! Thanks for the interest! Our latest results show that when applied to 350M model, ReLoRA can perform just as well as regular training. We are currently scaling up ReLoRA to test it on Pythia-1B with Eleuther.Ai. You can see the 1B code in dev branch.
> 
> ![W B Chart 7_19_2023, 11_00_07 AM](https://user-images.githubusercontent.com/2821124/254615390-2600c0e2-ee81-4ead-b341-f2e7ab6a600b.png)

Hey~ what is the result of the Pythia-1B?

**Comment by datalee** [comment]
6b model seem not work
