### ISSUE TITLE
Once this model is trained, how should I infer ? Is there an example script?

### ISSUE THREAD

**Issue by ScottishFold007** [Guitaricet/peft_pretraining#2]
Once this model is trained, how should I infer ? Is there an example script?
I'm having trouble loading the model using the following method：
![image](https://github.com/Guitaricet/relora/assets/36957508/8461a179-e1bd-42c1-a3ef-0c2b8804143e)

![image](https://github.com/Guitaricet/relora/assets/36957508/26792172-dc7a-46f3-9dcd-2538f7f8fa26)
It seems that this model lacks many parameters, can the actual prediction be good?

**Comment by Guitaricet** [comment]
Hi! Thank you for providing more details about your question.

Assuming `.merge_and_reinit()` was applied before the model was saved, you can use this code:

```
from peft_pretraining.modeling_llama import LlamaForCausalLM
model = LlamaForCausalLM.from_pretrained("path/to/model/save/dir")
```

Wrapping it with ReLoRA model is only needed for training.

**Comment by datalee** [comment]
.merge_and_reinit() maybe have some wrong？ It's a big difference compared to lora.
