### ISSUE TITLE
Inquiry About Minimum VRAM Requirement for ReLoRA Model Training

### ISSUE THREAD

**Issue by Njasa2k** [Guitaricet/peft_pretraining#3]
I recently came across your paper on "ReLoRA: Low-Rank Training for Efficient Neural Networks" but I'm unsure about the technical details, especially when it comes to hardware requirements. Could you provide some guidance on the minimum VRAM needed for implementing ReLoRA effectively?

**Comment by DumoeDss** [comment]
If pre-training a 7B model, how much gpu memory is needed?

**Comment by Guitaricet** [comment]
Hi! Most of the experiments in the paper (including 1B) used 2x3090 or 8x4090 setup with 24Gb RAM on each GPU.

However, a more precise answer to this question would depend on your existing hardware setup and training hparams, such as model size, amount of data to train on, distributed type used (DDP vs FSDP vs DDP + TP), and others.

My rule of thumb recommendation for a 7B model is at least 4 or 8 nodes of 8xA100 and additional non-trivial code optimizations such as ZeRO stage 3 or tensor parallel to increase training efficiency. You can find ZeRO stage 1 and other some other optimizations in a **non-stable** `dev` branch of the repository. However, my practical recommendation to train 7B models using ReLoRA would be to reimplement ReLoRA in an existing LLM training framework such as GPT-NeoX or LLM Foundry. The current repository was not built to scale to more than 1B parameters + 20B tokens.
