### ISSUE TITLE
实际任务相关的问题

### ISSUE THREAD

**Issue by wanghao-007** [Guitaricet/peft_pretraining#9]
老哥，这个插件，有没有 针对实际的一些任务做过测试，比如QA，summary。

**Comment by Guitaricet** [comment]
Hi! Sorry, I don't speak Mandarin. I translated your question and I will reply in English.

ReLoRA was developed and tested for LM-based pre-training. We have then compared ReLoRA-pretrained models to usual full-rank models by fine-tuning them (in a regular way) to GLUE tasks. The results are available in the appendix our updated paper on arxiv.

In terms of applying ReLoRA directly for downstream tasks, we are currently working on it and we see small, but consistent improvements over LoRA. We are currently planning to release the downstream fine-tuning with ReLoRA paper in October.

**Comment by gccnlp** [comment]
Hi @Guitaricet,
Could you kindly inform me when the code for downstream fine-tuning will be released?
